language: ruby

sudo: false

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"

cache: bundler

rvm:
 - 2.3.1

env:
 - DB=pgsql

services:
 - postgresql

test:
  adapter: postgresql
  database: ycms_test

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: 
# - bundle exec rspec spec

before_script:
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database ycms_test;' -U postgres
 - bundle update
 - bundle exec rake db:test:prepare

deploy:
  provider: heroku
  api_key:
    secure: "6c9068eb-a63a-44dd-a6ca-fa6b5b16e821"
  app: yadadya-development-ycms

notifications:
  slack: yadadya:dw75tQmpnDHUXVCabdc2RABS